apiVersion: v1
kind: Secret
metadata:
  name: taskflow-secrets
  namespace: taskflow
  labels:
    app.kubernetes.io/name: taskflow
type: Opaque
stringData:
  DATABASE_URL: "postgresql://taskflow:taskflow_k8s_password@postgres:5432/taskflow"
  DIRECT_DATABASE_URL: "postgresql://taskflow:taskflow_k8s_password@postgres:5432/taskflow"
  REDIS_URL: "redis://redis:6379"
  AUTH_SECRET: "taskflow-k8s-auth-secret-32chars!!"
  NEXTAUTH_SECRET: "taskflow-k8s-auth-secret-32chars!!"
  NEXTAUTH_URL: "http://taskflow-frontend:3000"
  JWT_SECRET: "taskflow-k8s-jwt-secret-32chars!!!"
  POSTGRES_DB: "taskflow"
  POSTGRES_USER: "taskflow"
  POSTGRES_PASSWORD: "taskflow_k8s_password"

